# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cd8Bz1_BjOY912zfeZtwVljrTHVFT2yB
"""

from google.colab import files
uploaded = files.upload()

from sklearn.metrics import ConfusionMatrixDisplay

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
!pip install xgboost
from xgboost import XGBClassifier

df = pd.read_csv("loan_data.csv")
print("Dataset Loaded ✅")
print("Shape:", df.shape)
df.head()

num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(exclude=np.number).columns
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)
print("Missing values handled ✅")

target_column = "loan_status"
X = df.drop(target_column, axis=1)
y = df[target_column]
X = pd.get_dummies(X, drop_first=True)
if y.dtype == "object":
    y = y.astype("category").cat.codes

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)
y_prob_lr = lr.predict_proba(X_test_scaled)[:,1]
print("=== Logistic Regression ===")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_lr)

plt.title("Confusion Matrix - Logistic Regression")
plt.show()

fpr, tpr, _ = roc_curve(y_test, y_prob_lr)
auc_score = roc_auc_score(y_test, y_prob_lr)
plt.figure()
plt.plot(fpr, tpr, label="AUC = %.2f" % auc_score)
plt.plot([0,1],[0,1])
plt.title("ROC - Logistic Regression")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.legend()
plt.show()

train_pred_lr = lr.predict(X_train_scaled)
train_acc_lr = accuracy_score(y_train, train_pred_lr)
test_acc_lr = accuracy_score(y_test, y_pred_lr)
print("Train Accuracy:", train_acc_lr)
print("Test Accuracy:", test_acc_lr)
print("Overfitting Gap:", train_acc_lr - test_acc_lr)

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
y_prob_rf = rf.predict_proba(X_test)[:,1]
print("=== Random Forest ===")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

# Create Confusion Matrix Display
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_rf)

plt.title("Confusion Matrix - Random Forest")
plt.show()

fpr, tpr, _ = roc_curve(y_test, y_prob_rf)
auc_score = roc_auc_score(y_test, y_prob_rf)

plt.figure()
plt.plot(fpr, tpr, label="AUC = %.2f" % auc_score)
plt.plot([0,1],[0,1])
plt.title("ROC - Random Forest")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.legend()
plt.show()

xgb = XGBClassifier(eval_metric="logloss")
xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)
y_prob_xgb = xgb.predict_proba(X_test)[:,1]

print("=== XGBoost ===")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

fpr, tpr, _ = roc_curve(y_test, y_prob_xgb)
auc_score = roc_auc_score(y_test, y_prob_xgb)

plt.figure()
plt.plot(fpr, tpr, label="AUC = %.2f" % auc_score)
plt.plot([0,1],[0,1])
plt.title("ROC - XGBoost")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.legend()
plt.show()

train_pred_xgb = xgb.predict(X_train)

train_acc_xgb = accuracy_score(y_train, train_pred_xgb)
test_acc_xgb = accuracy_score(y_test, y_pred_xgb)

print("Train Accuracy:", train_acc_xgb)
print("Test Accuracy:", test_acc_xgb)
print("Overfitting Gap:", train_acc_xgb - test_acc_xgb)

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_xgb)
plt.title("Confusion Matrix - XGBoost")
plt.show()
